server.document-root = "/var/www/localhost/htdocs"
server.port = 80
server.username = "lighttpd"
server.groupname = "lighttpd"

server.modules = (
  "mod_accesslog",
  "mod_alias",
  "mod_rewrite",
  "mod_proxy",
  "mod_wstunnel"
)

index-file.names = ("index.html")
accesslog.filename = "/dev/stdout"

$HTTP["url"] =~ "^/api($|/)" {
  proxy.server = (
    "" => (("host" => "backend", "port" => 3001))
  )
}

$HTTP["url"] =~ "^/ws($|/)" {
  wstunnel.server = (
    "" => (("host" => "backend", "port" => 3001))
  )
}

$HTTP["url"] !~ "^/(api|ws)($|/)" {
  url.rewrite-if-not-file = (
    "^/(.*)$" => "/index.html"
  )
}
